import React, { useState, useEffect, useRef } from 'react';
import {
  Send,
  Database,
  GitBranch,
  Layers,
  Sparkles,
  Info,
  CheckCircle2,
  AlertCircle,
  HelpCircle,
  Trash2,
  FileCode
} from 'lucide-react';
import { Header } from './components/Header.js';
import { RecommendationCard } from './components/RecommendationCard.js';
import { ClarifyingQuestionCard } from './components/ClarifyingQuestionCard.js';
import { StructuredInputView } from './components/StructuredInputModal.js';
import { DebugRetrievalPane } from './components/DebugRetrievalPane.js';
import { ChatMessage, EnvironmentalInput, RecommendationResponse } from './types.js';

export default function App() {
  const [activeTab, setActiveTab] = useState<'chat' | 'structured' | 'debug'>('chat');
  const [sessionId, setSessionId] = useState<string>(() => {
    return 'session_' + Math.random().toString(36).substring(2, 9);
  });

  const [inputMessage, setInputMessage] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [cumulativeContext, setCumulativeContext] = useState<EnvironmentalInput>({});
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages, isLoading]);

  // Initial welcome message from scientist system
  useEffect(() => {
    if (messages.length === 0) {
      setMessages([
        {
          id: 'welcome',
          sender: 'assistant',
          text: 'Welcome to the Darukaa.Earth AI Environmental Scientist system.\n\n' +
            'Every recommendation generated by this engine is strictly grounded in retrievable knowledge layers (FAO, IPCC, USDA), multi-variable causal reasoning (tracing >= 3 environmental variables), and empirical thresholds.\n\n' +
            'You can test scenarios using natural language or structured JSON input.',
          timestamp: new Date().toISOString()
        }
      ]);
    }
  }, []);

  const handleResetSession = () => {
    const newId = 'session_' + Math.random().toString(36).substring(2, 9);
    setSessionId(newId);
    setCumulativeContext({});
    setMessages([
      {
        id: 'welcome_' + newId,
        sender: 'assistant',
        text: 'Session state reset. Memory is clean. Please provide your environmental context (soil carbon %, climate/rainfall, land use/crop).',
        timestamp: new Date().toISOString()
      }
    ]);
  };

  const handleSendMessage = async (textToSend?: string, structuredData?: EnvironmentalInput) => {
    const text = textToSend !== undefined ? textToSend : inputMessage;
    if (!text.trim() && !structuredData) return;

    const userMsgId = Math.random().toString(36).substring(2, 9);
    const userMsg: ChatMessage = {
      id: userMsgId,
      sender: 'user',
      text: text || (structuredData ? 'Submitted Structured Environmental Input' : ''),
      structured_payload: structuredData,
      timestamp: new Date().toISOString()
    };

    setMessages((prev) => [...prev, userMsg]);
    if (textToSend === undefined) setInputMessage('');
    setIsLoading(true);

    try {
      const response = await fetch('/api/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          session_id: sessionId,
          message: text,
          structured_data: structuredData
        })
      });

      const data: RecommendationResponse = await response.json();

      if (data.session_context) {
        setCumulativeContext(data.session_context);
      }

      const assistantMsg: ChatMessage = {
        id: Math.random().toString(36).substring(2, 9),
        sender: 'assistant',
        text: data.is_clarifying_question
          ? (data.clarifying_question || '')
          : (data.recommendation || ''),
        recommendation_payload: data,
        timestamp: new Date().toISOString()
      };

      setMessages((prev) => [...prev, assistantMsg]);
    } catch (err: any) {
      console.error('Error in handleSendMessage:', err);
      const errorMsg: ChatMessage = {
        id: Math.random().toString(36).substring(2, 9),
        sender: 'assistant',
        text: 'System communication error: ' + (err.message || 'Unable to connect to reasoning engine'),
        timestamp: new Date().toISOString()
      };
      setMessages((prev) => [...prev, errorMsg]);
    } finally {
      setIsLoading(false);
    }
  };

  const handleStructuredSubmit = async (data: EnvironmentalInput) => {
    setActiveTab('chat');
    await handleSendMessage('', data);
  };

  const runPresetScenario = (scenario: string) => {
    if (scenario === 'brief_benchmark') {
      handleSendMessage(
        'My farm has 0.3% soil organic carbon, low rainfall, monoculture wheat in a semi-arid region.'
      );
    } else if (scenario === 'incomplete_query') {
      handleSendMessage('Biodiversity is declining on my land');
    } else if (scenario === 'refinement') {
      handleSendMessage('What if I switch to agroforestry instead?');
    } else if (scenario === 'pesticide_hazard') {
      handleSendMessage(
        'We apply 4.2 kg pesticide per hectare annually next to a stream on our cropland, with 0.8% SOC in sub-humid climate.'
      );
    }
  };

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 flex flex-col font-sans">
      {/* Header */}
      <Header
        activeTab={activeTab}
        setActiveTab={setActiveTab}
        onResetSession={handleResetSession}
        sessionId={sessionId}
      />

      {/* Main Container */}
      <main className="flex-1 max-w-7xl w-full mx-auto p-3 sm:p-6 flex flex-col">
        {activeTab === 'structured' && (
          <StructuredInputView onSubmit={handleStructuredSubmit} isLoading={isLoading} />
        )}

        {activeTab === 'debug' && <DebugRetrievalPane />}

        {activeTab === 'chat' && (
          <div className="flex-1 flex flex-col lg:flex-row gap-5 max-w-6xl mx-auto w-full">
            {/* Left/Main Column: Chat Stream */}
            <div className="flex-1 flex flex-col bg-slate-900/80 border border-slate-800/80 rounded-2xl overflow-hidden shadow-xl">
              {/* Quick Evaluation Scenario Bar */}
              <div className="bg-slate-850 p-2.5 sm:p-3 border-b border-slate-800 flex flex-wrap items-center gap-1.5 text-xs">
                <span className="text-slate-400 font-semibold flex items-center space-x-1 mr-1">
                  <Sparkles className="w-3.5 h-3.5 text-emerald-400" />
                  <span className="hidden sm:inline">Benchmark Evaluator Tests:</span>
                </span>
                <button
                  id="btn-test-benchmark"
                  onClick={() => runPresetScenario('brief_benchmark')}
                  className="px-2.5 py-1 rounded bg-slate-800 hover:bg-slate-700 text-emerald-300 border border-emerald-500/30 transition-colors"
                  title="Run exact benchmark scenario from brief"
                >
                  Brief Case: 0.3% SOC + Semi-Arid + Monoculture
                </button>
                <button
                  id="btn-test-incomplete"
                  onClick={() => runPresetScenario('incomplete_query')}
                  className="px-2.5 py-1 rounded bg-slate-800 hover:bg-slate-700 text-amber-300 border border-amber-500/30 transition-colors"
                  title="Test completeness checking & clarifying question"
                >
                  Test: Incomplete Query ('Biodiversity is declining')
                </button>
                <button
                  id="btn-test-refinement"
                  onClick={() => runPresetScenario('refinement')}
                  className="px-2.5 py-1 rounded bg-slate-800 hover:bg-slate-700 text-sky-300 border border-sky-500/30 transition-colors"
                  title="Test multi-turn context retention"
                >
                  Test: Agroforestry Refinement
                </button>
                <button
                  id="btn-test-pesticide"
                  onClick={() => runPresetScenario('pesticide_hazard')}
                  className="px-2.5 py-1 rounded bg-slate-800 hover:bg-slate-700 text-purple-300 border border-purple-500/30 transition-colors"
                  title="Test chemical runoff & riparian buffer"
                >
                  Test: 4.2 kg/ha Pesticide Runoff
                </button>
              </div>

              {/* Chat Message Stream */}
              <div className="flex-1 overflow-y-auto p-4 sm:p-5 space-y-4 max-h-[65vh] min-h-[420px]">
                {messages.map((msg) => (
                  <div
                    key={msg.id}
                    className={`flex flex-col ${
                      msg.sender === 'user' ? 'items-end' : 'items-start'
                    }`}
                  >
                    {msg.sender === 'user' ? (
                      <div className="max-w-[85%] bg-emerald-700/80 text-white rounded-2xl rounded-tr-none px-4 py-3 text-sm shadow-md border border-emerald-500/30">
                        {msg.structured_payload ? (
                          <div>
                            <div className="flex items-center space-x-1.5 mb-1.5 text-xs font-semibold text-emerald-200">
                              <FileCode className="w-3.5 h-3.5" />
                              <span>Structured Environmental Input Submitted:</span>
                            </div>
                            <pre className="bg-slate-950/70 p-2 rounded text-[11px] font-mono text-emerald-300 overflow-x-auto">
                              {JSON.stringify(msg.structured_payload, null, 2)}
                            </pre>
                          </div>
                        ) : (
                          <p className="whitespace-pre-wrap leading-relaxed">{msg.text}</p>
                        )}
                        <span className="text-[10px] text-emerald-200/70 block text-right mt-1 font-mono">
                          {new Date(msg.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                        </span>
                      </div>
                    ) : (
                      <div className="w-full max-w-full">
                        {msg.recommendation_payload?.is_clarifying_question ? (
                          <ClarifyingQuestionCard
                            payload={msg.recommendation_payload}
                            onSelectQuickAnswer={(ans) => handleSendMessage(ans)}
                          />
                        ) : msg.recommendation_payload ? (
                          <RecommendationCard payload={msg.recommendation_payload} />
                        ) : (
                          <div className="bg-slate-800/80 text-slate-200 rounded-2xl rounded-tl-none p-4 text-sm border border-slate-700/70 leading-relaxed whitespace-pre-line shadow">
                            {msg.text}
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                ))}

                {isLoading && (
                  <div className="flex items-center space-x-3 p-4 bg-slate-800/60 rounded-xl border border-slate-700/60 w-fit">
                    <div className="w-2.5 h-2.5 rounded-full bg-emerald-400 animate-pulse" />
                    <div className="w-2.5 h-2.5 rounded-full bg-emerald-400 animate-pulse delay-150" />
                    <div className="w-2.5 h-2.5 rounded-full bg-emerald-400 animate-pulse delay-300" />
                    <span className="text-xs text-slate-300 font-mono">
                      Querying Hybrid RAG knowledge layers & tracing causal graph...
                    </span>
                  </div>
                )}
                <div ref={messagesEndRef} />
              </div>

              {/* Chat Input Bar */}
              <div className="p-3 sm:p-4 bg-slate-900 border-t border-slate-800 flex items-center space-x-2">
                <input
                  id="input-user-message"
                  type="text"
                  value={inputMessage}
                  onChange={(e) => setInputMessage(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' && !e.shiftKey) {
                      e.preventDefault();
                      handleSendMessage();
                    }
                  }}
                  placeholder="Describe your land (e.g., 0.3% SOC, low rainfall, monoculture wheat in semi-arid region)..."
                  className="flex-1 bg-slate-950 border border-slate-700 rounded-xl px-4 py-2.5 text-sm text-slate-200 placeholder-slate-500 focus:outline-none focus:border-emerald-500 font-sans"
                  disabled={isLoading}
                />
                <button
                  id="btn-send-message"
                  onClick={() => handleSendMessage()}
                  disabled={isLoading || !inputMessage.trim()}
                  className="p-2.5 bg-emerald-600 hover:bg-emerald-500 disabled:opacity-40 text-white rounded-xl transition-colors shadow flex items-center justify-center"
                >
                  <Send className="w-4 h-4" />
                </button>
              </div>
            </div>

            {/* Right Column: Multi-Turn Cumulative Context & System Pipeline State */}
            <div className="w-full lg:w-72 flex flex-col space-y-4">
              {/* Context Memory Widget */}
              <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-4 shadow-lg text-xs">
                <div className="flex items-center justify-between pb-2 border-b border-slate-800 mb-3">
                  <div className="flex items-center space-x-1.5 font-bold text-slate-200 uppercase tracking-wider">
                    <Layers className="w-4 h-4 text-emerald-400" />
                    <span>Active Session Context</span>
                  </div>
                  <span className="text-[10px] text-slate-500 font-mono">SQLite Tracked</span>
                </div>

                {Object.keys(cumulativeContext).length === 0 ? (
                  <p className="text-slate-500 italic text-[11px]">
                    No environmental parameters accumulated yet. Enter values via chat or JSON to populate memory.
                  </p>
                ) : (
                  <div className="space-y-2">
                    {cumulativeContext.soil_organic_carbon_pct !== undefined && (
                      <div className="bg-slate-800/60 p-2 rounded border border-slate-700/60 flex justify-between items-center">
                        <span className="text-slate-400">Soil Organic Carbon:</span>
                        <span className="font-bold text-emerald-400 font-mono">
                          {cumulativeContext.soil_organic_carbon_pct}%
                        </span>
                      </div>
                    )}
                    {cumulativeContext.land_use && (
                      <div className="bg-slate-800/60 p-2 rounded border border-slate-700/60 flex justify-between items-center">
                        <span className="text-slate-400">Land Use / Crop:</span>
                        <span className="font-semibold text-slate-200 capitalize font-mono">
                          {cumulativeContext.land_use.replace('_', ' ')}
                        </span>
                      </div>
                    )}
                    {cumulativeContext.rainfall && (
                      <div className="bg-slate-800/60 p-2 rounded border border-slate-700/60 flex justify-between items-center">
                        <span className="text-slate-400">Rainfall:</span>
                        <span className="font-semibold text-slate-200 capitalize font-mono">
                          {cumulativeContext.rainfall}
                        </span>
                      </div>
                    )}
                    {cumulativeContext.region_climate && (
                      <div className="bg-slate-800/60 p-2 rounded border border-slate-700/60 flex justify-between items-center">
                        <span className="text-slate-400">Climate Zone:</span>
                        <span className="font-semibold text-sky-400 font-mono">
                          {cumulativeContext.region_climate}
                        </span>
                      </div>
                    )}
                    {cumulativeContext.soil_ph && (
                      <div className="bg-slate-800/60 p-2 rounded border border-slate-700/60 flex justify-between items-center">
                        <span className="text-slate-400">Soil pH:</span>
                        <span className="font-mono text-slate-200">{cumulativeContext.soil_ph}</span>
                      </div>
                    )}
                    {cumulativeContext.pesticide_intensity_kg_ha && (
                      <div className="bg-slate-800/60 p-2 rounded border border-slate-700/60 flex justify-between items-center">
                        <span className="text-slate-400">Pesticide:</span>
                        <span className="font-mono text-rose-400">{cumulativeContext.pesticide_intensity_kg_ha} kg/ha</span>
                      </div>
                    )}
                  </div>
                )}
              </div>

              {/* Engine Status Indicators */}
              <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-4 shadow-lg text-xs space-y-3">
                <div className="font-bold text-slate-200 uppercase tracking-wider pb-1.5 border-b border-slate-800 flex items-center space-x-1.5">
                  <Database className="w-4 h-4 text-emerald-400" />
                  <span>Knowledge Layer Specs</span>
                </div>

                <div className="space-y-1.5 text-[11px] text-slate-300">
                  <div className="flex justify-between">
                    <span className="text-slate-400">Indexed RAG Chunks:</span>
                    <span className="font-mono text-emerald-400 font-bold">35 Peer-Reviewed Chunks</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-400">Causal Graph Nodes:</span>
                    <span className="font-mono text-indigo-400 font-bold">7 Ecological Nodes</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-400">Variables Traced / Rec:</span>
                    <span className="font-mono text-amber-400 font-bold">&gt;= 3 Verified</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-400">Literature Citations:</span>
                    <span className="font-mono text-slate-300">FAO, IPCC, USDA, IPBES</span>
                  </div>
                </div>

                <div className="pt-2 border-t border-slate-800">
                  <button
                    onClick={() => setActiveTab('debug')}
                    className="w-full py-1.5 px-2.5 rounded bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white border border-slate-700 text-[11px] font-medium transition-colors"
                  >
                    Open RAG / Vector Inspector &rarr;
                  </button>
                </div>
              </div>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
